services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: wit-challenge-2020-rabbitmq
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/wit-challenge-2020/dados:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=juniorlatalisa
            - RABBITMQ_DEFAULT_PASS=ChallengeWIT@2020